services/web/project/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap

from project.config import get_config


bootstrap = Bootstrap()


def create_app(env="development", dotenv_path=None):
    app = Flask(__name__)

    config = get_config(env, dotenv_path=dotenv_path)

    app.config.from_object(config)

    bootstrap.init_app(app)

    from project.blueprints.errors import bp as errors_bp

    app.register_blueprint(errors_bp)

    from project.blueprints.index import bp as index_bp

    app.register_blueprint(index_bp)

    return app

services/web/project/blueprints/index/__init__.py
from flask import Blueprint

bp = Blueprint('index', __name__)

from project.blueprints.index import routes  # noqa: E402 F401

services/web/project/blueprints/index/routes.py
from flask import render_template, jsonify

from project.blueprints.index import bp


@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index/index.html', title='Home')


@bp.route('/ping')
def ping():
    return jsonify({"ping": "pong"}), 200

services/web/project/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - JanneJP.com{% else %}Welcome to JanneJP.com{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('index.index') }}">JanneJP.com</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('index.index') }}">Home</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{{ url_for('index.index') }}">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

services/web/project/templates/index/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Hello World!</h1>
{% endblock %}